# -*- coding: utf-8 -*-
"""DRSS_EnterpriseAI_part_1_databuild.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzCE9nLd-p6PE9jdkDHW2q-AS7O2XzFm

# **Demonstration of Best practises fror AI enterprises- Part 1 | Building Data Layers**

*   Identification of datasets
*   Creating unified data structure
*   Creating unified context structure

## 1. Setup and Dataset Identification

First, we'll install the `datasets` library from Hugging Face, which is essential for loading the datasets.
"""

# Install necessary libraries
!pip install datasets pandas jsonlines Faker

"""Next, we'll define a configuration for 10 high-quality medical datasets from Hugging Face. This configuration includes the dataset name on Hugging Face and the specific splits we might want to load. I've chosen a variety of datasets covering different medical NLP tasks (e.g., Q&A, named entity recognition, text classification).

"""

!pip install jsonlines
from datasets import load_dataset, DatasetDict
import pandas as pd
import json
import jsonlines

DATASET_CONFIG = {
    'medmcqa': {
        'hf_path': 'medmcqa',
        'splits': ['train', 'validation'],
        'description': 'Multiple-choice question answering for medical exams.'
    },
    'squad': {
        'hf_path': 'squad',
        'splits': ['train', 'validation'],
        'description': 'Question answering dataset, can be adapted for medical QA.'
    },
    'multi_nli_entailment': {
        'hf_path': 'multi_nli',
        'splits': ['train', 'validation'],
        'description': 'Natural Language Inference dataset, useful for medical entailment tasks.'
    },
    'pubmed_qa': {
        'hf_path': 'pubmed_qa',
        'subset': 'pqa_labeled', # Specific subset required
        'splits': ['train', 'validation', 'test'],
        'description': 'PubMed QA dataset for biomedical research questions.'
    },
    # 'medqa_usmle': {
    #     'hf_path': 'flax-medical-nlp/medqa_usmle',
    #     'splits': ['train', 'validation'],
    #     'description': 'Medical Question Answering dataset (USMLE style).'
    # },
    'ncbi_disease': {
        'hf_path': 'ncbi_disease', # Corrected path
        'splits': ['train', 'validation', 'test'],
        'description': 'Named entity recognition for diseases.'
    },
    'bc5cdr': {
        'hf_path': 'bc5cdr', # Corrected path
        'splits': ['train', 'validation', 'test'], # Simplified splits, original had bc5cdr_disease/chemical
        'description': 'Named entity recognition for chemicals and diseases.'
    },
    # 'clinical_notes': {
    #     'hf_path': 'flax-medical-nlp/clinical-notes',
    #     'splits': ['train'],
    #     'description': 'Clinical notes from US radiology reports.'
    # },
    # 'medical_dialogue_de': {
    #     'hf_path': 'medical_dialog',
    #     'subset': 'en_de',
    #     'splits': ['train', 'validation', 'test'],
    #     'description': 'Medical dialogue translation (English to German).'
    # },
    'sem_eval_2010_task_8': {
        'hf_path': 'sem_eval_2010_task_8',
        'splits': ['train', 'validation', 'test'],
        'description': 'Semantic Relation Extraction (general NLP, can be applied to medical).'
    }
}

# Note: Some datasets are general NLP datasets but are often used as baselines or for transfer learning in medical NLP after fine-tuning.

import random

# Configuration for data building process
databuild_config = {
    'output_json_filename': 'merged_medical_datasets.json',
    'output_jsonld_filename': 'merged_medical_datasets.jsonld',
    'sample_size': 100,  # Number of examples to sample from the merged dataset
    'sampled_output_json_filename': 'sampled_medical_datasets.json'
}

"""## 2. Dataset Loader Function

Now, let's create a generic function that can load any of these datasets based on the configuration. This function will return a dictionary of `datasets.Dataset` objects, one for each specified split.

"""

def load_medical_dataset(dataset_key: str) -> dict:
    """Loads a medical dataset from Hugging Face based on the DATASET_CONFIG.

    Args:
        dataset_key: The key corresponding to the dataset in DATASET_CONFIG.

    Returns:
        A dictionary where keys are split names (e.g., 'train', 'validation')
        and values are `datasets.Dataset` objects. Returns an empty dict if
        the dataset_key is not found or loading fails.
    """
    if dataset_key not in DATASET_CONFIG:
        print(f"Error: Dataset key '{dataset_key}' not found in configuration.")
        return {}

    config_entry = DATASET_CONFIG[dataset_key]
    hf_path = config_entry['hf_path']
    splits = config_entry['splits']
    subset = config_entry.get('subset')

    loaded_splits = {}
    print(f"Loading dataset: {hf_path} (Key: {dataset_key})")
    try:
        if subset:
            full_dataset = load_dataset(hf_path, subset)
        else:
            full_dataset = load_dataset(hf_path)

        for split in splits:
            if split in full_dataset:
                loaded_splits[split] = full_dataset[split]
            else:
                print(f"Warning: Split '{split}' not found for dataset '{hf_path}'.")
        print(f"Successfully loaded splits: {list(loaded_splits.keys())} for {dataset_key}")
        return loaded_splits
    except Exception as e:
        print(f"Failed to load dataset '{hf_path}' (Key: {dataset_key}): {e}")
        return {}

"""### Demonstration of Loading a Dataset

Let's load the `ncbi_disease` dataset and inspect its structure.

"""

# Load a sample dataset
ncbid_dataset_splits = load_medical_dataset('ncbi_disease')

if ncbid_dataset_splits:
    print("\n--- ncbi_disease Train Split Info ---")
    display(ncbid_dataset_splits['train'])
    print("\n--- First example from ncbi_disease Train Split ---")
    display(ncbid_dataset_splits['train'][0])
    print("\n--- Schema for ncbi_disease Train Split ---")
    display(ncbid_dataset_splits['train'].features)

"""## 3. Load All Datasets

Now, let's load all the datasets specified in our `DATASET_CONFIG` using the `load_medical_dataset` function. This might take some time depending on your internet connection and the size of the datasets.
"""

all_loaded_datasets = {}
for key in DATASET_CONFIG:
    dataset_splits = load_medical_dataset(key)
    if dataset_splits:
        all_loaded_datasets[key] = dataset_splits

print(f"\nSuccessfully loaded {len(all_loaded_datasets)} out of {len(DATASET_CONFIG)} datasets.")

# Display the structure of one of the newly loaded datasets (e.g., pubmed_qa train split)
if 'pubmed_qa' in all_loaded_datasets and 'train' in all_loaded_datasets['pubmed_qa']:
    print("\n--- Sample from pubmed_qa Train Split ---")
    display(all_loaded_datasets['pubmed_qa']['train'][0])

"""## 4. Define Common Format and Merge Datasets

To ensure consistency across different medical datasets, we need to define a common, standardized JSON format. This format will facilitate easier analysis, model training, and integration. We'll then create functions to transform each dataset's examples into this common structure.

Our common format will aim to capture essential information like:
- `id`: A unique identifier for the example.
- `text`: The primary text content (e.g., clinical note, question, sentence).
- `labels`: A list of entities or classifications relevant to the text (e.g., disease names, answer types).
- `type`: The type of data (e.g., 'question_answering', 'named_entity_recognition', 'text_classification').
- `metadata`: A dictionary for any additional, dataset-specific information.

"""

# Define the common schema
COMMON_FORMAT_SCHEMA = {
    "id": "",
    "text": "",
    "labels": [],
    "type": "", # e.g., 'named_entity_recognition', 'question_answering', 'text_classification'
    "metadata": {} # For any additional dataset-specific information
}

def _get_spans_from_tokens_and_ner_tags(tokens, ner_tags, id_to_ner_label):
    """Helper to reconstruct text and get entity spans from tokens and NER tags.
    Adapted for datasets that provide tokens and BIO-labeled ner_tags.
    """
    text = " ".join(tokens)
    labels = []
    current_entity = []
    current_type = None
    start_idx = 0

    for i, (token, tag_id) in enumerate(zip(tokens, ner_tags)):
        absolute_start = text.find(token, start_idx)
        if absolute_start == -1: # Should not happen if tokens form the text
             absolute_start = start_idx # Fallback
        absolute_end = absolute_start + len(token)

        tag_name = id_to_ner_label.get(tag_id, 'O')

        if tag_name.startswith('B-'):
            if current_entity:
                labels.append({
                    'text': " ".join(current_entity),
                    'entity_type': current_type,
                    'offsets': {'start': current_start_offset, 'end': current_end_offset}
                })
            current_type = tag_name[2:]
            current_entity = [token]
            current_start_offset = absolute_start
            current_end_offset = absolute_end
        elif tag_name.startswith('I-') and current_type == tag_name[2:]:
            current_entity.append(token)
            current_end_offset = absolute_end
        else:
            if current_entity:
                labels.append({
                    'text': " ".join(current_entity),
                    'entity_type': current_type,
                    'offsets': {'start': current_start_offset, 'end': current_end_offset}
                })
            current_entity = []
            current_type = None

        start_idx = absolute_end # Update start index for next token search
        if i < len(tokens) - 1: # account for space between tokens
            start_idx += 1

    if current_entity:
        labels.append({
            'text': " ".join(current_entity),
            'entity_type': current_type,
            'offsets': {'start': current_start_offset, 'end': current_end_offset}
        })
    return text, labels

def convert_to_common_format(dataset_key: str, example: dict) -> dict:
    """Converts a single example from a specific dataset into the common format.

    Args:
        dataset_key: The key of the dataset in DATASET_CONFIG.
        example: The original example dictionary from the dataset.

    Returns:
        A dictionary formatted according to COMMON_FORMAT_SCHEMA.
    """
    common_example = COMMON_FORMAT_SCHEMA.copy()
    common_example['metadata'] = {'original_dataset': dataset_key}

    if dataset_key == 'ncbi_disease':
        common_example['id'] = str(example['id'])
        ner_tag_labels = {0: 'O', 1: 'B-Disease', 2: 'I-Disease'}
        text, labels = _get_spans_from_tokens_and_ner_tags(example['tokens'], example['ner_tags'], ner_tag_labels)
        common_example['text'] = text
        common_example['type'] = 'named_entity_recognition'
        common_example['labels'] = labels

    elif dataset_key == 'pubmed_qa':
        common_example['id'] = example['pubid'] if 'pubid' in example else ''
        common_example['text'] = example['question']
        common_example['type'] = 'question_answering'
        common_example['labels'] = [example['long_answer']] if 'long_answer' in example else []
        common_example['metadata']['context'] = example['context'] if 'context' in example else ''
        common_example['metadata']['final_decision'] = example['final_decision'] if 'final_decision' in example else ''

    elif dataset_key == 'medqa_usmle': # Updated medical_qa to medqa_usmle
        common_example['id'] = str(example['id'])
        common_example['text'] = example['question']
        common_example['type'] = 'question_answering'
        common_example['labels'] = [example['answer']] if 'answer' in example else []

    elif dataset_key == 'bc5cdr':
        common_example['id'] = str(example['id'])
        ner_tag_labels = {0: 'O', 1: 'B-Disease', 2: 'I-Disease', 3: 'B-Chemical', 4: 'I-Chemical'}
        text, labels = _get_spans_from_tokens_and_ner_tags(example['tokens'], example['ner_tags'], ner_tag_labels)
        common_example['text'] = text
        common_example['type'] = 'named_entity_recognition'
        common_example['labels'] = labels

    elif dataset_key == 'medmcqa':
        common_example['id'] = str(example['id'])
        common_example['text'] = example['question']
        common_example['type'] = 'multiple_choice_qa'
        # For multiple choice, store options and correct answer in metadata
        options = [example['opa'], example['opb'], example['opc'], example['opd']]
        correct_answer_idx = example['cop'] # 0, 1, 2, 3
        correct_answer = options[correct_answer_idx]
        common_example['labels'] = [correct_answer]
        common_example['metadata']['options'] = options
        common_example['metadata']['correct_answer_index'] = correct_answer_idx

    elif dataset_key == 'clinical_notes':
        common_example['id'] = str(example['id'])
        common_example['text'] = example['text']
        common_example['type'] = 'clinical_note'
        common_example['labels'] = [] # This dataset might need further processing for labels
        common_example['metadata']['report_type'] = example['report_type']
        common_example['metadata']['gender'] = example['gender']

    elif dataset_key == 'multi_nli_entailment':
        common_example['id'] = str(example['pairID'])
        common_example['text'] = example['premise'] + " [SEP] " + example['hypothesis']
        common_example['type'] = 'natural_language_inference'
        label_map = {0: 'entailment', 1: 'neutral', 2: 'contradiction'}
        common_example['labels'] = [label_map.get(example['label'], 'unknown')]
        common_example['metadata']['premise'] = example['premise']
        common_example['metadata']['hypothesis'] = example['hypothesis']

    elif dataset_key == 'medical_dialogue_de': # New medical dialogue translation dataset
        common_example['id'] = str(hash(example['translation']['en'] + example['translation']['de'])) # Unique ID
        common_example['text'] = example['translation']['en']
        common_example['type'] = 'machine_translation'
        common_example['labels'] = [example['translation']['de']]
        common_example['metadata']['source_lang'] = 'en'
        common_example['metadata']['target_lang'] = 'de'

    elif dataset_key == 'sem_eval_2010_task_8': # New relation extraction dataset
        # sem_eval_2010_task_8 has integer labels, need to map them to string names
        # The dataset object will have features['labels'].names
        # Assuming we can get the label names dynamically or hardcode if stable.
        # For now, let's hardcode a few common ones if needed, or assume a direct map to string
        # based on the dataset's features. The original dataset provides `labels` as integer indices.
        # The 'labels' feature in `sem_eval_2010_task_8` is a ClassLabel, so example['labels'] will be the integer ID.
        # To get the string name, we would typically need access to the dataset.features['labels'].names
        # For simplicity, assuming a generic conversion for now, or will refine if needed.
        label_names = [
            'Other', 'Cause-Effect(e1,e2)', 'Cause-Effect(e2,e1)',
            'Instrument-Agency(e1,e2)', 'Instrument-Agency(e2,e1)',
            'Product-Producer(e1,e2)', 'Product-Producer(e2,e1)',
            'Content-Container(e1,e2)', 'Content-Container(e2,e1)',
            'Entity-Origin(e1,e2)', 'Entity-Origin(e2,e1)',
            'Entity-Destination(e1,e2)', 'Entity-Destination(e2,e1)',
            'Component-Whole(e1,e2)', 'Component-Whole(e2,e1)',
            'Member-Collection(e1,e2)', 'Member-Collection(e2,e1)'
        ]
        common_example['id'] = str(hash(example['sentence']))
        common_example['text'] = example['sentence']
        common_example['type'] = 'relation_extraction'
        common_example['labels'] = [label_names[example['labels']]] if 'labels' in example and example['labels'] < len(label_names) else []

    elif dataset_key == 'squad':
        common_example['id'] = example['id']
        common_example['text'] = example['context'] + " [SEP] " + example['question']
        common_example['type'] = 'question_answering'
        # For SQuAD, the answer is usually a span within the context
        answers = example['answers']['text']
        answer_starts = example['answers']['answer_start']
        labels = []
        for ans, start in zip(answers, answer_starts):
            labels.append({'text': ans, 'offsets': {'start': start, 'end': start + len(ans)}})
        common_example['labels'] = labels
        common_example['metadata']['context'] = example['context']
        common_example['metadata']['question'] = example['question']

    return common_example


def merge_datasets_to_common_format(loaded_datasets: dict) -> list:
    """Merges all loaded datasets into a single list of examples in the common format.

    Args:
        loaded_datasets: A dictionary of loaded datasets, as returned by load_medical_dataset.

    Returns:
        A list of dictionaries, each formatted according to COMMON_FORMAT_SCHEMA.
    """
    merged_data = []
    for dataset_key, splits in loaded_datasets.items():
        print(f"Processing dataset: {dataset_key}")
        for split_name, dataset_obj in splits.items():
            print(f"  - Processing split: {split_name} (Size: {len(dataset_obj)} examples)")
            # Apply the conversion function across the dataset
            converted_split = dataset_obj.map(
                lambda x: convert_to_common_format(dataset_key, x),
                remove_columns=dataset_obj.column_names # Remove original columns
            )
            # Add split name to metadata for tracking
            for example in converted_split:
                example['metadata']['original_split'] = split_name
                merged_data.append(example)
    return merged_data

# Perform the merging
merged_medical_data = merge_datasets_to_common_format(all_loaded_datasets)

print(f"\nTotal merged examples: {len(merged_medical_data)}")
print("\n--- Sample of merged data (first 3 examples) ---")
for i, example in enumerate(merged_medical_data[:3]):
    print(f"Example {i+1}: {json.dumps(example, indent=2)}")

# Save the merged data to a JSON file
output_json_path = 'merged_medical_datasets.json'
with jsonlines.open(output_json_path, mode='w') as writer:
    writer.write_all(merged_medical_data)

print(f"\nMerged data saved to '{output_json_path}'")

"""### 4. Create JSON-LD Version of the Merged Data

JSON-LD (JSON for Linking Data) is a lightweight Linked Data format. It's designed to be easily usable by JSON-based data programming environments, and provides a way to express semantically rich metadata. We will convert our common JSON format into a simple JSON-LD structure.

"""

def convert_to_jsonld(common_data_list: list, context_url: str = "https://schema.org/") -> list:
    """Converts a list of common formatted examples into JSON-LD format.

    Args:
        common_data_list: A list of dictionaries in the COMMON_FORMAT_SCHEMA.
        context_url: The URL for the JSON-LD context.

    Returns:
        A list of dictionaries, each formatted as JSON-LD.
    """
    jsonld_data = []
    for example in common_data_list:
        jsonld_entry = {
            "@context": context_url,
            "@id": f"urn:example:{example['id']}",
            "@type": "DatasetRecord", # A generic type for our merged records
            "name": example['text'],
            "description": f"Record of type {example['type']} from {example['metadata'].get('original_dataset', 'unknown dataset')}",
            "keywords": [label['entity_type'] for label in example['labels'] if isinstance(label, dict) and 'entity_type' in label] if example['labels'] else [],
            "url": None, # Placeholder, could be linked to original source if available
            "additionalProperty": []
        }

        # Add 'text' if it exists and is a string
        if 'text' in example and isinstance(example['text'], str):
            jsonld_entry['mainEntity'] = {
                "@type": "CreativeWork",
                "text": example['text']
            }

        # Add labels as additional properties or entities
        if example['labels']:
            for label_entry in example['labels']:
                if isinstance(label_entry, dict):
                    # For structured labels (e.g., NER spans)
                    entity_type = label_entry.get('entity_type', 'Entity')
                    jsonld_entry['additionalProperty'].append({
                        "@type": "PropertyValue",
                        "name": entity_type,
                        "value": label_entry.get('text'),
                        "description": f"Original offset: {label_entry.get('offsets')}" if 'offsets' in label_entry else None
                    })
                else:
                    # For simple string labels
                    jsonld_entry['additionalProperty'].append({
                        "@type": "PropertyValue",
                        "name": "label",
                        "value": str(label_entry)
                    })

        # Add metadata properties
        if example['metadata']:
            for key, value in example['metadata'].items():
                if isinstance(value, (str, int, float, bool)):
                    jsonld_entry['additionalProperty'].append({
                        "@type": "PropertyValue",
                        "name": key,
                        "value": str(value)
                    })
                elif isinstance(value, list):
                    for item in value:
                        jsonld_entry['additionalProperty'].append({
                            "@type": "PropertyValue",
                            "name": key,
                            "value": str(item)
                        })

        jsonld_data.append(jsonld_entry)
    return jsonld_data

# Convert the merged data to JSON-LD
merged_medical_data_jsonld = convert_to_jsonld(merged_medical_data)

print(f"\nConverted {len(merged_medical_data_jsonld)} examples to JSON-LD.")
print("\n--- Sample of JSON-LD data (first 2 examples) ---")
for i, example in enumerate(merged_medical_data_jsonld[:2]):
    print(f"Example {i+1}: {json.dumps(example, indent=2)}")

# Save the JSON-LD data to a file
output_jsonld_path = 'merged_medical_datasets.jsonld'
with jsonlines.open(output_jsonld_path, mode='w') as writer:
    writer.write_all(merged_medical_data_jsonld)

print(f"\nJSON-LD data saved to '{output_jsonld_path}'")

def sample_merged_dataset(input_json_path: str, n_sample: int, output_sampled_json_path: str):
    """
    Samples N_sample rows from a merged JSON dataset and saves it to a new file.

    Args:
        input_json_path: Path to the full merged JSON dataset.
        n_sample: Number of samples to draw.
        output_sampled_json_path: Path to save the sampled JSON dataset.
    """
    print(f"\n--- Sampling {n_sample} examples from '{input_json_path}' ---")
    all_examples = []
    try:
        with jsonlines.open(input_json_path, mode='r') as reader:
            for obj in reader:
                all_examples.append(obj)
    except FileNotFoundError:
        print(f"Error: Input file '{input_json_path}' not found.")
        return

    if not all_examples:
        print("No examples found in the input file. Skipping sampling.")
        return

    if n_sample >= len(all_examples):
        print(f"Warning: Sample size ({n_sample}) is greater than or equal to total examples ({len(all_examples)}). Saving all examples as sampled.")
        sampled_data = all_examples
    else:
        sampled_data = random.sample(all_examples, n_sample)

    with jsonlines.open(output_sampled_json_path, mode='w') as writer:
        writer.write_all(sampled_data)
    print(f"Sampled data ({len(sampled_data)} examples) saved to '{output_sampled_json_path}'")

"""### 5. Orchestration Function to Perform All Steps

Finally, we'll encapsulate all the above logic into a single, modular function that can be called to perform the entire process: loading, converting to common format, merging, and saving both JSON and JSON-LD outputs.

"""

def process_medical_datasets(dataset_config: dict, build_config: dict):
    """Orchestrates the loading, merging, and saving of medical datasets.

    Args:
        dataset_config: The configuration dictionary for datasets (DATASET_CONFIG).
        build_config: The configuration dictionary for file names and sampling.
    """
    print("--- Starting Medical Dataset Processing ---")

    # Extract filenames from build_config
    output_json_filename = build_config.get('output_json_filename', 'merged_medical_datasets.json')
    output_jsonld_filename = build_config.get('output_jsonld_filename', 'merged_medical_datasets.jsonld')
    sample_size = build_config.get('sample_size', 100)
    sampled_output_json_filename = build_config.get('sampled_output_json_filename', 'sampled_medical_datasets.json')

    # 1. Load all datasets
    all_loaded_datasets = {}
    for key in dataset_config:
        dataset_splits = load_medical_dataset(key)
        if dataset_splits:
            all_loaded_datasets[key] = dataset_splits
    print(f"\nSuccessfully loaded {len(all_loaded_datasets)} out of {len(dataset_config)} datasets after initial loading attempts.")

    # 2. Merge datasets to common format
    merged_medical_data = merge_datasets_to_common_format(all_loaded_datasets)
    print(f"\nTotal merged examples: {len(merged_medical_data)}")

    # 3. Save full merged data to JSON
    with jsonlines.open(output_json_filename, mode='w') as writer:
        writer.write_all(merged_medical_data)
    print(f"Full merged data saved to '{output_json_filename}'")

    # 4. Convert and save to JSON-LD
    merged_medical_data_jsonld = convert_to_jsonld(merged_medical_data)
    with jsonlines.open(output_jsonld_filename, mode='w') as writer:
        writer.write_all(merged_medical_data_jsonld)
    print(f"JSON-LD data saved to '{output_jsonld_filename}'")

    # 5. Sample the merged dataset
    sample_merged_dataset(output_json_filename, sample_size, sampled_output_json_filename)

    print("--- Medical Dataset Processing Complete ---")

# Example of how to call the orchestration function
process_medical_datasets(DATASET_CONFIG, databuild_config)

print("\nAll required functions have been defined. You can now call `process_medical_datasets(DATASET_CONFIG, databuild_config)` to run the full pipeline.")



"""**Now we are ready for part 2 for creatinf test, train and red-teaming datasets**"""

